apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: deployment-patch.yaml

resources:
- ../base

images:
- name: simple-app
  newTag: 1.0.0

configMapGenerator:
  - name: config
  literals:
    - NAME=simple-app