apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: patch-deployment-name

replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.NAME
    targets:
      - select:
          kind: Deployment
          name: simple-app
        fieldPaths:
          - metadata.name
          - metadata.labels.[app]
          - spec.selector.matchLabels.[app]
          - spec.template.metadata.labels.[app]
          - spec.template.spec.containers.[name=simple-app].name
