apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: patch-deployment-name

replacements:
  - path: "../app/deployment.yaml"
  - source:
      kind: ConfigMap
      name: html-config
      fieldPath: data.NAME
    targets:
      - select:
          kind: Deployment
          name: simple-app
        fieldPaths:
          - metadata.name
