kind: Kustomization

resources:
  - ../base


configMapGenerator:
  - name: config
    literals:
      - NAME=simple-app-2
  - name: html-config
    behavior: replace
    files:
      - index.html


transformers:
  - ../transformers

