apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <html>
      <head>
        <title>Teste de ArgoCD</title>
      </head>
      <body>
        <h1>Olá, Rei da Infra</h1>
        <p>Agora você é um mestre DevOps.</p>
      </body>
    </html>
