apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Rótulos comuns aplicados a todos os recursos
commonLabels:
  app: simple-app

resources:
  - deployment.yaml
  - service.yaml

# Gerador de ConfigMap
configMapGenerator:
  - name: simple-app-app
    literals:
      - NAME=simple-app
