resources:
  - configMap.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NAME=simple-app
      - CONFIG-MAP-NAME=html-config
      - VERSION=1.0.0
      - IMAGE=nginx
      - MEM-MIN=128Mi
      - MEM-MAX=256Mi
      - CPU-MIN=100m
      - CPU-MAX=500m
